server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sportstore
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
        flush_mode: COMMIT

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB

  cache:
    type: redis
    redis:
      time-to-live: 86400000
      cache-null-values: false

  data:
    redis:
      host: localhost
      port: 6379

  # Cấu hình SMTP cho Gmail (thêm mới)
  mail:
    host: smtp.gmail.com
    port: 587
    username: caothang8107@gmail.com
    password: vvmz uwiq vzso rdnz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  security:
    oauth2:
      client:
        registration:
          google:
                        scope:
              - openid
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

jwt:
  secret-key: thanggdev123456789thanggdev123456789

sepay:
  bank:
    name: VietinBank
    accountNumber: 109874753814
    accountHolder: Cao Chiến Thắng

cloudinary:
  cloud-name: dm1p5ocbz
  api-key: 923887916441132
  api-secret: pCrHymqBTOlruX0MqVAlF2kdi-8

logging:
  level:
    org.springframework.security: DEBUG
    com.sportshop.sportstore.security: DEBUG  # Sửa từ "sprotshop" thành "sportshop"
    org.springframework.web: DEBUG